<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Drag  Drop your files or  Browse</name>
   <tag></tag>
   <elementGuidId>ac2a33c1-322d-4055-9f75-cb5fc397f669</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='file' and @name='filepond']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.filepond--drop-label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>943bd6bc-eb9d-4ad9-96c2-ac0e7a965e27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>filepond--drop-label</value>
      <webElementGuid>edbb451c-59c4-446e-a64d-15aefa0e0dbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Drag &amp; Drop your files or  Browse </value>
      <webElementGuid>8743b756-9991-4b0f-801a-202cdb1c0e31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;data.image&quot;)/div[@class=&quot;h-full w-full&quot;]/div[@class=&quot;filepond--root filepond--hopper&quot;]/div[@class=&quot;filepond--drop-label&quot;]</value>
      <webElementGuid>ed54a364-c178-4411-9b9b-36f6f3ec18d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='data.image']/div/div/div</value>
      <webElementGuid>d8e0975b-9828-4898-b605-81e09f8fa005</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gambar Menu'])[1]/following::div[5]</value>
      <webElementGuid>f45a40ba-7e3b-4079-adc6-f9e39e394f15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp'])[1]/following::div[11]</value>
      <webElementGuid>ba5e528a-8ec2-424f-a2e0-b926a5aff152</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/div/div/div</value>
      <webElementGuid>e1470942-a628-4d00-9d4a-62d8357eedf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Drag &amp; Drop your files or  Browse ' or . = 'Drag &amp; Drop your files or  Browse ')]</value>
      <webElementGuid>a62ec50d-627e-4d7d-805d-c32b957f9099</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
