<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Drag  Drop your files or  Browse</name>
   <tag></tag>
   <elementGuidId>05aa427d-5a4a-4227-a483-bdfa92e7f843</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='filepond--drop-label-ehoyhyujx']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#filepond--drop-label-ehoyhyujx</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>58c06ce9-f3e6-481b-81c2-36106697d29a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>filepond--browser-ehoyhyujx</value>
      <webElementGuid>4ddef4e4-5dda-4bcb-871c-922a97cef1fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>filepond--drop-label-ehoyhyujx</value>
      <webElementGuid>ab996931-81ab-4ab5-a768-03f8877defc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Drag &amp; Drop your files or  Browse </value>
      <webElementGuid>51b5adb5-48ef-4e7f-a006-4a04f56436a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filepond--drop-label-ehoyhyujx&quot;)</value>
      <webElementGuid>832b525e-4294-4ae7-8f40-52ba57e2599c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='filepond--drop-label-ehoyhyujx']</value>
      <webElementGuid>7f7a850e-75f7-4f39-8ad5-3ac23a34edbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='data.image']/div/div/div/label</value>
      <webElementGuid>23c95373-dce6-4b49-9333-8bddf4573333</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gambar Menu'])[1]/following::label[1]</value>
      <webElementGuid>357c9956-b83e-4d7f-aac0-5437dcb922d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp'])[1]/following::label[1]</value>
      <webElementGuid>9331acd7-e03a-4af8-82b7-ea12b7f68ba4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Files'])[1]/preceding::label[1]</value>
      <webElementGuid>82f72cab-f584-439f-b4fa-e95ca45a9e21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Drag &amp; Drop your files or']/parent::*</value>
      <webElementGuid>3cb6d32d-d083-4f68-8e06-e1c288347aae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/label</value>
      <webElementGuid>b2f2ebe7-22f1-4a16-b818-b3aa18a6d314</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'filepond--drop-label-ehoyhyujx' and (text() = 'Drag &amp; Drop your files or  Browse ' or . = 'Drag &amp; Drop your files or  Browse ')]</value>
      <webElementGuid>d9a4c934-2d91-4341-81af-7d803c3b52ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
