<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Create</name>
   <tag></tag>
   <elementGuidId>ddfb3cef-a63e-49d2-a187-9d180f50a516</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='key-bindings-1']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.fi-btn-label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>37956a30-58e7-499e-911b-36b9f50dc4ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x-show</name>
      <type>Main</type>
      <value>! isProcessing</value>
      <webElementGuid>dc60d5ee-b0ff-46e4-88b0-fccf8aa6a909</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fi-btn-label</value>
      <webElementGuid>bdaac89f-ae3e-4628-a182-56d6176f2357</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
        Create
    </value>
      <webElementGuid>0d297d68-97e0-45bf-90d8-7a291c4d61ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;key-bindings-1&quot;)/span[@class=&quot;fi-btn-label&quot;]</value>
      <webElementGuid>7999a30e-0780-4ecb-b6c0-0ff652cb8240</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='key-bindings-1']/span</value>
      <webElementGuid>268ce441-b2d8-4436-8d70-594bd6cfafd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Files'])[1]/following::span[1]</value>
      <webElementGuid>cd5fa8b5-c933-401f-a9bc-541b86cfefbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ceker.jpg Upload complete'])[1]/following::span[1]</value>
      <webElementGuid>65626027-5efb-41c4-ba43-fa50c4006697</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Uploading file...'])[1]/preceding::span[1]</value>
      <webElementGuid>0247bbce-f271-4e0f-abd5-cfaee68848c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create &amp; create another'])[1]/preceding::span[2]</value>
      <webElementGuid>8af77b38-9d83-4c96-8d00-4b26eb7b958e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button/span</value>
      <webElementGuid>5b5f6811-bd9b-4538-adec-03d142b4da7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '
        Create
    ' or . = '
        Create
    ')]</value>
      <webElementGuid>ab93fdc4-20dc-43f0-9368-88033e42f05b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
