<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Browse</name>
   <tag></tag>
   <elementGuidId>d1102dd5-35cb-4108-b6da-4dbc16647833</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='filepond--drop-label-ehoyhyujx']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.filepond--label-action</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d751293e-0bea-4e94-a403-1c3e38681779</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>filepond--label-action</value>
      <webElementGuid>e13ec188-db4e-4f08-b630-7668cdd80f20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>497434b9-c926-4c15-9fb0-ba1ce79eaa89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Browse </value>
      <webElementGuid>570115a4-9c7d-4014-b2b6-f17a09af03ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;filepond--drop-label-ehoyhyujx&quot;)/span[@class=&quot;filepond--label-action&quot;]</value>
      <webElementGuid>5bbb59f6-3227-4e41-bba9-7ab03572b4cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//label[@id='filepond--drop-label-ehoyhyujx']/span</value>
      <webElementGuid>ae934a33-0018-4ce7-9055-1ca2e501c1fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gambar Menu'])[1]/following::span[1]</value>
      <webElementGuid>99bbae31-3aa7-41e3-8945-5439b6a4dafb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Files'])[1]/preceding::span[2]</value>
      <webElementGuid>738882ac-d845-4608-b8bd-f7c8f2eb9264</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create'])[2]/preceding::span[2]</value>
      <webElementGuid>b0585c7b-7c04-4435-9eb1-81f9e2811dc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Browse']/parent::*</value>
      <webElementGuid>67b6b861-89ea-4d50-97ff-483ca70a8f46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/label/span</value>
      <webElementGuid>b85cb9e8-b533-43d1-9a30-84ed04b85868</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' Browse ' or . = ' Browse ')]</value>
      <webElementGuid>7e293e9c-9dd3-44e1-bfc5-cb4833d95be3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//label[@id='filepond--drop-label-w7nhlzdhx']/span</value>
      <webElementGuid>d3b1e10f-f805-4de7-8eac-1d44135f3ec0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
