<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Welcome to Our Restaurant_customer-name</name>
   <tag></tag>
   <elementGuidId>11d75115-b2b4-4e2c-8b4c-6ce925aab244</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#customer-name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='customer-name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>87dbc10e-1a23-461a-a477-ffbcb49b0e66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f2a049bb-b937-4aa6-9042-7d4c553a48ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>customer-name</value>
      <webElementGuid>4c9bd553-97a5-4782-9cb5-f72d81e6d9d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter your name</value>
      <webElementGuid>6c16a0bd-2aec-41f8-843d-d1456c8b57b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full px-4 py-3 border border-gray-300 rounded focus:outline-none focus:ring-2 focus:ring-primary</value>
      <webElementGuid>da2a11b9-bfc3-4eb7-b8f3-6463bdd8183c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;customer-name&quot;)</value>
      <webElementGuid>7bd42a9a-d41a-4abb-92c4-b2b8d5230a2b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='customer-name']</value>
      <webElementGuid>781dffba-3256-4ff3-9ae4-8487944870d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='welcome-form']/div/input</value>
      <webElementGuid>d8030938-ddac-43d1-ae3d-301d2b751ee3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>9b9ad315-6ae9-4223-8f35-ba7a389932e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'customer-name' and @placeholder = 'Enter your name']</value>
      <webElementGuid>2b742d9d-c8c0-43a1-8303-47b3b706010d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
