<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Rp24.000</name>
   <tag></tag>
   <elementGuidId>7b2f3594-194e-427e-9542-d7de428938aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#total</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='total']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c5a60e50-74b2-4e90-a0ac-f6fd036488e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>total</value>
      <webElementGuid>12cf744a-6e5b-4da1-a727-c1917c819cce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-semibold</value>
      <webElementGuid>dee7bfc1-d207-45f7-93c2-2e4cf0f869dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rp24.000</value>
      <webElementGuid>6787e2fc-55fe-4dac-b60d-54dddab5a03e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;total&quot;)</value>
      <webElementGuid>54da9fb1-d748-476d-b6f2-64ff9251dc2b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='total']</value>
      <webElementGuid>7b10936e-5414-40b2-89b7-86f52578b300</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cart-items']/div[2]/div/span[2]</value>
      <webElementGuid>f12b2777-d666-4873-8110-c2cbf3669ddd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total'])[1]/following::span[1]</value>
      <webElementGuid>340c72d3-1330-48cb-b1a3-e2459c4f784f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp24.000'])[1]/following::span[2]</value>
      <webElementGuid>4b90a35a-30d5-4ecd-84aa-bf249e6577a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buat Struk'])[1]/preceding::span[1]</value>
      <webElementGuid>6b34a557-4929-42ce-bfe3-bb2798ef7c49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='STRUK PEMBAYARAN'])[1]/preceding::span[1]</value>
      <webElementGuid>f3f4fa25-3055-43ff-be2b-209eca2c930c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]</value>
      <webElementGuid>a1a7ef40-851e-4961-b620-087e62f1dd45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'total' and (text() = 'Rp24.000' or . = 'Rp24.000')]</value>
      <webElementGuid>416001ca-b37e-44bf-85ee-e24e7aeb4a5b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
